export const SET_SELECTION_RANGE = 'SET_SELECTION_RANGE';
export const SET_CHORD_SHEET = 'SET_CHORD_SHEET';
export const TRANSPOSE_UP = 'TRANSPOSE_UP';
export const TRANSPOSE_DOWN = 'TRANSPOSE_DOWN';
export const SWITCH_TO_SHARP = 'CHANGE_TO_SHARP';
export const SWITCH_TO_FLAT = 'CHANGE_TO_FLAT';
